### ISSUE TITLE
PingBack not working

### ISSUE THREAD

**Issue by elschick** [kokspflanze/PaymentAPI#6]
Hi hab ein anderes Problem irgendwie bekomme ich den Pingback von der Paymentwall nicht hin, 
Pingback wasn't successful. Reason: HTTP status code is different from 200

Hab die module.config entsprechend angepasst sec. key usw. ausserdem hab ich versucht über autoload.config mit der payment.local.php zu arbeiten, die Paymentwall wird mir angezeigt usw. aber Pingback funktioniert nicht....

Ausserdem hab ich ne 2. frage wie kann ich es einstellen das man z.B Silk kaufen kann und diese dann auch automatisch über die API dem jeweiligen account gutgeschrieben werden? :(

**Comment by kokspflanze** [comment]
please check the donate log in adminpanel there you see the error.

about your other question you have to setup everything at the donate provider and do the following https://github.com/kokspflanze/pserverCMSFull/blob/master/doc/general-setup/DONATE.md#overwrite-the-current-donate-template

if you have more questions, about payments please ask the donate provider, how he work internal. questions about the module/cms gitterchat or github=]

**Comment by elschick** [comment]
Ich versteh das nicht ganz, hab Paymentwall vorher auch schon genutzt mit ner API dort hat er mir dann in meine DB alle infos geschrieben und nach nem erfolgreichen Pingback die "Silk" gutgeschrieben, hier bekomme ich nichtmal nen erfolgreichen pingback

**Comment by kokspflanze** [comment]
check what is written in your donate-log, there you see what is wrong, without these info i can not help.

**Comment by kokspflanze** [comment]
@elschick problem solved?
